/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo16_contador;

import java.awt.Color;


/**
 *
 * @author ASUS
 */
public class Classe_Janela extends javax.swing.JFrame {
    /**
     * Creates new form Classe_Janela
     */
    //construtor da classe janela
    public Classe_Janela() {
        initComponents();
        
        getContentPane().setBackground(Color.RED);
    
        ////////////////////////////////////////////////////////
        Thread gThread = new Thread() {
            public void run() {
                int numero = 0;
                int aumento = 1;

                while (true) {
                    numero+= aumento;
                    String sNumero = String.valueOf(numero);
                    jLabel1.setText(sNumero);
                    jLabel1.setFont(new java.awt.Font("Tahoma", 1, numero));
                    
                    if (numero > 200)
                        aumento--;
                    if (numero < 0)
                        aumento++;
                    
                    try {Thread.sleep(100);} catch (InterruptedException ex) {}
                }
            }
        }; 
        gThread.start(); //lança a instância
           
    }
    /////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contador");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
                
